services:
  - type: web
    name: ledo-sports-academy
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false # This will be set manually in Render dashboard
      - key: JWT_SECRET
        sync: false # This will be set manually in Render dashboard 